parameters:
#    galeria_subidor.example.class: Galeria\SubidorBundle\Example

services:
#    galeria_subidor.example:
#        class: %galeria_subidor.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
