parameters:
#    galeria_subidor2.example.class: Galeria\Subidor2Bundle\Example

services:
#    galeria_subidor2.example:
#        class: %galeria_subidor2.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
