parameters:
#    galeria_galeria.example.class: Galeria\GaleriaBundle\Example

services:
#    galeria_galeria.example:
#        class: %galeria_galeria.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
